[package]
name = "solutions"
version = "0.1.0"
edition = "2021"

[dependencies]
z3 = { version = "0.19.6", features = ["static-link-z3"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
